name: Build and Package on Windows
run-name: ${{ github.actor }} try to build and package the Automation Tool per release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Create release
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          cmd /c call venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          cmd /c call venv\Scripts\activate
          pyinstaller automation_tool.spec
          cmd /c call venv\Scripts\deactivate

      - name: Copy additional folders to dist
        run: |
          IF EXIST dist (
            xcopy input dist\input /E /H /C /I
            xcopy script dist\script /E /H /C /I
          )

      - name: Run Inno Setup
        uses: callebstrom/inno-setup-cli-action@6.2.1
        with:
          path: automation_tool.iss

      - name: Get tag name
        id: tag_name
        run: |
          echo "Extracting tag name from GITHUB_REF..."
          $tagName = $env:GITHUB_REF -replace 'refs/tags/', ''
          Write-Output "::set-output name=tag_version::$tagName"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: automation_tool_${{ steps.tag_name.outputs.tag_version }}
          path: dist/automation_tool.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_version }}
          release_name: Release ${{ steps.tag_name.outputs.tag_version }}
          body: Release version ${{ steps.tag_name.outputs.tag_version }} some update to enhance the quality

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/automation_tool_installer.exe
          asset_name: automation_tool_installer_${{ steps.tag_name.outputs.tag_version }}.exe
          asset_content_type: application/octet-stream
